<?php
/**
 * AccountCallbackTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant\Client;

/**
 * AccountCallbackTest Class Doc Comment
 *
 * @category    Class */
// * @description The account callback. See the &#39;AccountCallbacks&#39; type.
/**
 * @package     Voximplant\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountCallbackTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AccountCallback"
     */
    public function testAccountCallback()
    {

    }

    /**
     * Test attribute "callback_id"
     */
    public function testPropertyCallbackId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {

    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {

    }

    /**
     * Test attribute "account_email"
     */
    public function testPropertyAccountEmail()
    {

    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {

    }

    /**
     * Test attribute "account_first_name"
     */
    public function testPropertyAccountFirstName()
    {

    }

    /**
     * Test attribute "account_last_name"
     */
    public function testPropertyAccountLastName()
    {

    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "account_document_verified"
     */
    public function testPropertyAccountDocumentVerified()
    {

    }

    /**
     * Test attribute "account_is_frozen"
     */
    public function testPropertyAccountIsFrozen()
    {

    }

    /**
     * Test attribute "activate_successful"
     */
    public function testPropertyActivateSuccessful()
    {

    }

    /**
     * Test attribute "call_history_report"
     */
    public function testPropertyCallHistoryReport()
    {

    }

    /**
     * Test attribute "card_expired"
     */
    public function testPropertyCardExpired()
    {

    }

    /**
     * Test attribute "card_expires_in_month"
     */
    public function testPropertyCardExpiresInMonth()
    {

    }

    /**
     * Test attribute "card_payment"
     */
    public function testPropertyCardPayment()
    {

    }

    /**
     * Test attribute "card_payment_failed"
     */
    public function testPropertyCardPaymentFailed()
    {

    }

    /**
     * Test attribute "js_fail"
     */
    public function testPropertyJsFail()
    {

    }

    /**
     * Test attribute "min_balance"
     */
    public function testPropertyMinBalance()
    {

    }

    /**
     * Test attribute "regulation_address_verified"
     */
    public function testPropertyRegulationAddressVerified()
    {

    }

    /**
     * Test attribute "renewed_subscriptions"
     */
    public function testPropertyRenewedSubscriptions()
    {

    }

    /**
     * Test attribute "reset_account_password_request"
     */
    public function testPropertyResetAccountPasswordRequest()
    {

    }

    /**
     * Test attribute "sip_registration_fail"
     */
    public function testPropertySipRegistrationFail()
    {

    }

    /**
     * Test attribute "stagnant_account"
     */
    public function testPropertyStagnantAccount()
    {

    }

    /**
     * Test attribute "subscription_is_frozen"
     */
    public function testPropertySubscriptionIsFrozen()
    {

    }

    /**
     * Test attribute "subscription_is_detached"
     */
    public function testPropertySubscriptionIsDetached()
    {

    }

    /**
     * Test attribute "transaction_history_report"
     */
    public function testPropertyTransactionHistoryReport()
    {

    }

    /**
     * Test attribute "uncharged_tariff"
     */
    public function testPropertyUnchargedTariff()
    {

    }

    /**
     * Test attribute "unverified_subscription_detached"
     */
    public function testPropertyUnverifiedSubscriptionDetached()
    {

    }

}
