<?php
/**
 * AccountInfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant;

/**
 * AccountInfoTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The GetAccountInfo function result.
/**
 * @package     Voximplant
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountInfoTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AccountInfoType"
     */
    public function testAccountInfoType()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {

    }

    /**
     * Test attribute "account_email"
     */
    public function testPropertyAccountEmail()
    {

    }

    /**
     * Test attribute "account_first_name"
     */
    public function testPropertyAccountFirstName()
    {

    }

    /**
     * Test attribute "account_last_name"
     */
    public function testPropertyAccountLastName()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {

    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {

    }

    /**
     * Test attribute "min_balance_to_notify"
     */
    public function testPropertyMinBalanceToNotify()
    {

    }

    /**
     * Test attribute "account_notifications"
     */
    public function testPropertyAccountNotifications()
    {

    }

    /**
     * Test attribute "tariff_changing_notifications"
     */
    public function testPropertyTariffChangingNotifications()
    {

    }

    /**
     * Test attribute "news_notifications"
     */
    public function testPropertyNewsNotifications()
    {

    }

    /**
     * Test attribute "billing_address_name"
     */
    public function testPropertyBillingAddressName()
    {

    }

    /**
     * Test attribute "billing_address_country_code"
     */
    public function testPropertyBillingAddressCountryCode()
    {

    }

    /**
     * Test attribute "billing_address_address"
     */
    public function testPropertyBillingAddressAddress()
    {

    }

    /**
     * Test attribute "billing_address_zip"
     */
    public function testPropertyBillingAddressZip()
    {

    }

    /**
     * Test attribute "billing_address_phone"
     */
    public function testPropertyBillingAddressPhone()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

    /**
     * Test attribute "frozen"
     */
    public function testPropertyFrozen()
    {

    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {

    }

    /**
     * Test attribute "credit_limit"
     */
    public function testPropertyCreditLimit()
    {

    }

    /**
     * Test attribute "tariff_id"
     */
    public function testPropertyTariffId()
    {

    }

    /**
     * Test attribute "tariff_name"
     */
    public function testPropertyTariffName()
    {

    }

    /**
     * Test attribute "periodic_charge"
     */
    public function testPropertyPeriodicCharge()
    {

    }

    /**
     * Test attribute "next_charge"
     */
    public function testPropertyNextCharge()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "support_robokassa"
     */
    public function testPropertySupportRobokassa()
    {

    }

    /**
     * Test attribute "support_bank_card"
     */
    public function testPropertySupportBankCard()
    {

    }

    /**
     * Test attribute "support_invoice"
     */
    public function testPropertySupportInvoice()
    {

    }

    /**
     * Test attribute "account_custom_data"
     */
    public function testPropertyAccountCustomData()
    {

    }

    /**
     * Test attribute "access_entries"
     */
    public function testPropertyAccessEntries()
    {

    }

    /**
     * Test attribute "with_access_entries"
     */
    public function testPropertyWithAccessEntries()
    {

    }

    /**
     * Test attribute "send_js_error"
     */
    public function testPropertySendJsError()
    {

    }

}
