<?php
/**
 * ACDSessionInfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant\Client;

/**
 * ACDSessionInfoTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The GetACDHistory function result item.
/**
 * @package     Voximplant\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ACDSessionInfoTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ACDSessionInfoType"
     */
    public function testACDSessionInfoType()
    {

    }

    /**
     * Test attribute "acd_session_history_id"
     */
    public function testPropertyAcdSessionHistoryId()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "begin_time"
     */
    public function testPropertyBeginTime()
    {

    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {

    }

    /**
     * Test attribute "acd_queue_id"
     */
    public function testPropertyAcdQueueId()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "waiting_duration"
     */
    public function testPropertyWaitingDuration()
    {

    }

    /**
     * Test attribute "in_service_duration"
     */
    public function testPropertyInServiceDuration()
    {

    }

    /**
     * Test attribute "after_service_duration"
     */
    public function testPropertyAfterServiceDuration()
    {

    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {

    }

}
