<?php
/**
 * AdminRoleTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant\Client;

/**
 * AdminRoleTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The GetAdminRoles function result.
/**
 * @package     Voximplant\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdminRoleTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AdminRoleType"
     */
    public function testAdminRoleType()
    {

    }

    /**
     * Test attribute "admin_role_id"
     */
    public function testPropertyAdminRoleId()
    {

    }

    /**
     * Test attribute "admin_role_name"
     */
    public function testPropertyAdminRoleName()
    {

    }

    /**
     * Test attribute "admin_role_active"
     */
    public function testPropertyAdminRoleActive()
    {

    }

    /**
     * Test attribute "system_role"
     */
    public function testPropertySystemRole()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "allowed_entries"
     */
    public function testPropertyAllowedEntries()
    {

    }

    /**
     * Test attribute "denied_entries"
     */
    public function testPropertyDeniedEntries()
    {

    }

}
