<?php
/**
 * AttachedPhoneInfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AttachedPhoneInfoTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The GetPhoneNumbers function result item.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AttachedPhoneInfoTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AttachedPhoneInfoType"
     */
    public function testAttachedPhoneInfoType()
    {

    }

    /**
     * Test attribute "phone_id"
     */
    public function testPropertyPhoneId()
    {

    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {

    }

    /**
     * Test attribute "phone_price"
     */
    public function testPropertyPhonePrice()
    {

    }

    /**
     * Test attribute "phone_country_code"
     */
    public function testPropertyPhoneCountryCode()
    {

    }

    /**
     * Test attribute "phone_next_renewal"
     */
    public function testPropertyPhoneNextRenewal()
    {

    }

    /**
     * Test attribute "phone_purchase_date"
     */
    public function testPropertyPhonePurchaseDate()
    {

    }

    /**
     * Test attribute "deactivated"
     */
    public function testPropertyDeactivated()
    {

    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {

    }

    /**
     * Test attribute "auto_charge"
     */
    public function testPropertyAutoCharge()
    {

    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {

    }

    /**
     * Test attribute "application_name"
     */
    public function testPropertyApplicationName()
    {

    }

    /**
     * Test attribute "rule_id"
     */
    public function testPropertyRuleId()
    {

    }

    /**
     * Test attribute "rule_name"
     */
    public function testPropertyRuleName()
    {

    }

    /**
     * Test attribute "category_name"
     */
    public function testPropertyCategoryName()
    {

    }

    /**
     * Test attribute "required_verification"
     */
    public function testPropertyRequiredVerification()
    {

    }

    /**
     * Test attribute "verification_status"
     */
    public function testPropertyVerificationStatus()
    {

    }

    /**
     * Test attribute "unverified_hold_until"
     */
    public function testPropertyUnverifiedHoldUntil()
    {

    }

    /**
     * Test attribute "can_be_used"
     */
    public function testPropertyCanBeUsed()
    {

    }

}
