<?php
/**
 * CalculatedTransactionHistoryDataTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplamt\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplamt\Client;

/**
 * CalculatedTransactionHistoryDataTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The HistoryReportType.calculated_data object on HistoryReportType.history_type&#x3D;&#x3D;&#39;transactions&#39;
/**
 * @package     Voximplamt\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CalculatedTransactionHistoryDataTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CalculatedTransactionHistoryDataType"
     */
    public function testCalculatedTransactionHistoryDataType()
    {

    }

    /**
     * Test attribute "transaction_count"
     */
    public function testPropertyTransactionCount()
    {

    }

    /**
     * Test attribute "total_transaction_count"
     */
    public function testPropertyTotalTransactionCount()
    {

    }

    /**
     * Test attribute "start_balance"
     */
    public function testPropertyStartBalance()
    {

    }

    /**
     * Test attribute "end_balance"
     */
    public function testPropertyEndBalance()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "user_name"
     */
    public function testPropertyUserName()
    {

    }

    /**
     * Test attribute "is_checked"
     */
    public function testPropertyIsChecked()
    {

    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {

    }

}
