<?php
/**
 * CallInfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CallInfoTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The call info.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallInfoTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CallInfoType"
     */
    public function testCallInfoType()
    {

    }

    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {

    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {

    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {

    }

    /**
     * Test attribute "local_number"
     */
    public function testPropertyLocalNumber()
    {

    }

    /**
     * Test attribute "remote_number"
     */
    public function testPropertyRemoteNumber()
    {

    }

    /**
     * Test attribute "remote_number_type"
     */
    public function testPropertyRemoteNumberType()
    {

    }

    /**
     * Test attribute "incoming"
     */
    public function testPropertyIncoming()
    {

    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {

    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {

    }

    /**
     * Test attribute "record_url"
     */
    public function testPropertyRecordUrl()
    {

    }

    /**
     * Test attribute "media_server_address"
     */
    public function testPropertyMediaServerAddress()
    {

    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {

    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {

    }

}
