<?php
/**
 * CallListDetailTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CallListDetailTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description Detailing job telephone calls
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallListDetailTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CallListDetailType"
     */
    public function testCallListDetailType()
    {

    }

    /**
     * Test attribute "list_id"
     */
    public function testPropertyListId()
    {

    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {

    }

    /**
     * Test attribute "start_execution_time"
     */
    public function testPropertyStartExecutionTime()
    {

    }

    /**
     * Test attribute "finish_execution_time"
     */
    public function testPropertyFinishExecutionTime()
    {

    }

    /**
     * Test attribute "result_data"
     */
    public function testPropertyResultData()
    {

    }

    /**
     * Test attribute "last_attempt"
     */
    public function testPropertyLastAttempt()
    {

    }

    /**
     * Test attribute "attmepts_left"
     */
    public function testPropertyAttmeptsLeft()
    {

    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

}
