<?php
/**
 * CallSessionInfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant\Client;

/**
 * CallSessionInfoTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The GetCallHistory function result item.
/**
 * @package     Voximplant\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallSessionInfoTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CallSessionInfoType"
     */
    public function testCallSessionInfoType()
    {

    }

    /**
     * Test attribute "call_session_history_id"
     */
    public function testPropertyCallSessionHistoryId()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {

    }

    /**
     * Test attribute "initiator_address"
     */
    public function testPropertyInitiatorAddress()
    {

    }

    /**
     * Test attribute "media_server_address"
     */
    public function testPropertyMediaServerAddress()
    {

    }

    /**
     * Test attribute "log_file_url"
     */
    public function testPropertyLogFileUrl()
    {

    }

    /**
     * Test attribute "finish_reason"
     */
    public function testPropertyFinishReason()
    {

    }

    /**
     * Test attribute "calls"
     */
    public function testPropertyCalls()
    {

    }

    /**
     * Test attribute "other_resource_usage"
     */
    public function testPropertyOtherResourceUsage()
    {

    }

    /**
     * Test attribute "records"
     */
    public function testPropertyRecords()
    {

    }

}
