<?php
/**
 * ClonedAccountTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant\Client;

/**
 * ClonedAccountTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The cloned account info.
/**
 * @package     Voximplant\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClonedAccountTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ClonedAccountType"
     */
    public function testClonedAccountType()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {

    }

    /**
     * Test attribute "account_email"
     */
    public function testPropertyAccountEmail()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {

    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {

    }

    /**
     * Test attribute "scenarios"
     */
    public function testPropertyScenarios()
    {

    }

    /**
     * Test attribute "applications"
     */
    public function testPropertyApplications()
    {

    }

    /**
     * Test attribute "acd_queues"
     */
    public function testPropertyAcdQueues()
    {

    }

    /**
     * Test attribute "acd_skills"
     */
    public function testPropertyAcdSkills()
    {

    }

    /**
     * Test attribute "admin_roles"
     */
    public function testPropertyAdminRoles()
    {

    }

    /**
     * Test attribute "admin_users"
     */
    public function testPropertyAdminUsers()
    {

    }

}
