<?php
/**
 * HistoryReportTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HistoryReportTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The history report info.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HistoryReportTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "HistoryReportType"
     */
    public function testHistoryReportType()
    {

    }

    /**
     * Test attribute "history_report_id"
     */
    public function testPropertyHistoryReportId()
    {

    }

    /**
     * Test attribute "history_type"
     */
    public function testPropertyHistoryType()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "format"
     */
    public function testPropertyFormat()
    {

    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {

    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {

    }

    /**
     * Test attribute "file_size"
     */
    public function testPropertyFileSize()
    {

    }

    /**
     * Test attribute "download_size"
     */
    public function testPropertyDownloadSize()
    {

    }

    /**
     * Test attribute "download_count"
     */
    public function testPropertyDownloadCount()
    {

    }

    /**
     * Test attribute "last_downloaded"
     */
    public function testPropertyLastDownloaded()
    {

    }

    /**
     * Test attribute "store_until"
     */
    public function testPropertyStoreUntil()
    {

    }

    /**
     * Test attribute "session_count"
     */
    public function testPropertySessionCount()
    {

    }

    /**
     * Test attribute "total_session_count"
     */
    public function testPropertyTotalSessionCount()
    {

    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {

    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {

    }

    /**
     * Test attribute "calculated_data"
     */
    public function testPropertyCalculatedData()
    {

    }

}
