<?php
/**
 * RegulationAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplamt\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplamt\Client;

/**
 * RegulationAddressTest Class Doc Comment
 *
 * @category    Class */
// * @description The RegulationAddress record
/**
 * @package     Voximplamt\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RegulationAddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RegulationAddress"
     */
    public function testRegulationAddress()
    {

    }

    /**
     * Test attribute "regulation_address_id"
     */
    public function testPropertyRegulationAddressId()
    {

    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {

    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "phone_category_name"
     */
    public function testPropertyPhoneCategoryName()
    {

    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "owner_country_code"
     */
    public function testPropertyOwnerCountryCode()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "zip_code"
     */
    public function testPropertyZipCode()
    {

    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {

    }

    /**
     * Test attribute "builder_number"
     */
    public function testPropertyBuilderNumber()
    {

    }

    /**
     * Test attribute "builder_latter"
     */
    public function testPropertyBuilderLatter()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "reject_message"
     */
    public function testPropertyRejectMessage()
    {

    }

    /**
     * Test attribute "phone_region_code"
     */
    public function testPropertyPhoneRegionCode()
    {

    }

}
