<?php
/**
 * SIPRegistrationTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant\Client;

/**
 * SIPRegistrationTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description Detailing SIP registration
/**
 * @package     Voximplant\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SIPRegistrationTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SIPRegistrationType"
     */
    public function testSIPRegistrationType()
    {

    }

    /**
     * Test attribute "sip_registration_id"
     */
    public function testPropertySipRegistrationId()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "application_id"
     */
    public function testPropertyApplicationId()
    {

    }

    /**
     * Test attribute "application_name"
     */
    public function testPropertyApplicationName()
    {

    }

    /**
     * Test attribute "rule_id"
     */
    public function testPropertyRuleId()
    {

    }

    /**
     * Test attribute "rule_name"
     */
    public function testPropertyRuleName()
    {

    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {

    }

    /**
     * Test attribute "proxy"
     */
    public function testPropertyProxy()
    {

    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {

    }

    /**
     * Test attribute "auth_user"
     */
    public function testPropertyAuthUser()
    {

    }

    /**
     * Test attribute "outbound_proxy"
     */
    public function testPropertyOutboundProxy()
    {

    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {

    }

    /**
     * Test attribute "status_code"
     */
    public function testPropertyStatusCode()
    {

    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {

    }

    /**
     * Test attribute "deactivated"
     */
    public function testPropertyDeactivated()
    {

    }

    /**
     * Test attribute "next_subscription_renewal"
     */
    public function testPropertyNextSubscriptionRenewal()
    {

    }

    /**
     * Test attribute "purchase_date"
     */
    public function testPropertyPurchaseDate()
    {

    }

    /**
     * Test attribute "subscription_price"
     */
    public function testPropertySubscriptionPrice()
    {

    }

}
