<?php
/**
 * SubscriptionsToChargeTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SubscriptionsToChargeTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The GetMoneyAmountToCharge function result field.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionsToChargeTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SubscriptionsToChargeType"
     */
    public function testSubscriptionsToChargeType()
    {

    }

    /**
     * Test attribute "subscription_amount"
     */
    public function testPropertySubscriptionAmount()
    {

    }

    /**
     * Test attribute "subscription_type"
     */
    public function testPropertySubscriptionType()
    {

    }

    /**
     * Test attribute "subscription_description"
     */
    public function testPropertySubscriptionDescription()
    {

    }

    /**
     * Test attribute "subscription_auto_charge"
     */
    public function testPropertySubscriptionAutoCharge()
    {

    }

    /**
     * Test attribute "subscription_next_renewal"
     */
    public function testPropertySubscriptionNextRenewal()
    {

    }

}
