<?php
/**
 * UserInfoTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Voximplant\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Voximplant\Client;

/**
 * UserInfoTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description The GetUsers function result.
/**
 * @package     Voximplant\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserInfoTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UserInfoType"
     */
    public function testUserInfoType()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "user_name"
     */
    public function testPropertyUserName()
    {

    }

    /**
     * Test attribute "user_display_name"
     */
    public function testPropertyUserDisplayName()
    {

    }

    /**
     * Test attribute "user_active"
     */
    public function testPropertyUserActive()
    {

    }

    /**
     * Test attribute "parent_accounting"
     */
    public function testPropertyParentAccounting()
    {

    }

    /**
     * Test attribute "two_factor_auth_required"
     */
    public function testPropertyTwoFactorAuthRequired()
    {

    }

    /**
     * Test attribute "mobile_phone"
     */
    public function testPropertyMobilePhone()
    {

    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {

    }

    /**
     * Test attribute "user_custom_data"
     */
    public function testPropertyUserCustomData()
    {

    }

    /**
     * Test attribute "applications"
     */
    public function testPropertyApplications()
    {

    }

    /**
     * Test attribute "skills"
     */
    public function testPropertySkills()
    {

    }

    /**
     * Test attribute "acd_queues"
     */
    public function testPropertyAcdQueues()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

}
