<?php
/**
 * ManagingAccountsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Voximplamt\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant HTTP API
 *
 * Voximplant HTTP API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@voximplant.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Voximplamt\Client;

use \Voximplamt\Client\Configuration;
use \Voximplamt\Client\ApiClient;
use \Voximplamt\Client\ApiException;
use \Voximplamt\Client\ObjectSerializer;

/**
 * ManagingAccountsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Voximplamt\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ManagingAccountsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for chargeAccount
     *
     * .
     *
     */
    public function testChargeAccount()
    {

    }

    /**
     * Test case for confirmAccountPasswordChange
     *
     * .
     *
     */
    public function testConfirmAccountPasswordChange()
    {

    }

    /**
     * Test case for getAccountDocuments
     *
     * .
     *
     */
    public function testGetAccountDocuments()
    {

    }

    /**
     * Test case for getAccountInfo
     *
     * .
     *
     */
    public function testGetAccountInfo()
    {

    }

    /**
     * Test case for getCurrencyRate
     *
     * .
     *
     */
    public function testGetCurrencyRate()
    {

    }

    /**
     * Test case for getMoneyAmountToCharge
     *
     * .
     *
     */
    public function testGetMoneyAmountToCharge()
    {

    }

    /**
     * Test case for getResourcePrice
     *
     * .
     *
     */
    public function testGetResourcePrice()
    {

    }

    /**
     * Test case for getSubscriptionPrice
     *
     * .
     *
     */
    public function testGetSubscriptionPrice()
    {

    }

    /**
     * Test case for sendAccountPasswordChangeRequest
     *
     * .
     *
     */
    public function testSendAccountPasswordChangeRequest()
    {

    }

    /**
     * Test case for setAccountDocument
     *
     * .
     *
     */
    public function testSetAccountDocument()
    {

    }

    /**
     * Test case for setAccountInfo
     *
     * .
     *
     */
    public function testSetAccountInfo()
    {

    }

}
